filter:
  excluded_paths:
    - test/*

build:
  dependencies:
    before:
      - pip3 install cleo==0.6.8
      - pip3 install coverage
      - pip3 install mysql-connector
      - pip3 install PyStratum-Backend
      - pip3 install PyStratum-Cli
      - pip3 install PyStratum-Common
      - pip3 install PyStratum-Middle

  nodes:
    analysis:
      tests:
        before:
          - mysql -u root -e "create database if not exists test;"
          - mysql -u root -e "create user 'test'@'localhost' identified by 'test';"
          - mysql -u root -e "grant all on test.*  to 'test'@'localhost';"
          - mysql -u root -e "set global binlog_format = 'row';"
          - mysql -u root -e "set global log_bin_trust_function_creators = 1;"
          - cat test/ddl/create_tables.sql | mysql -utest -ptest test
        override:
          - command: coverage run -m unittest discover -s test -p *Test.py
            coverage:
              file: '.coverage'
              config_file: '.coveragerc'
              format: 'py-cc'
          - py-scrutinizer-run

