/**
 * Test for designation insert_many.
 *
 * @type insert_many TST_TEMPO field_int,field_smallint,field_mediumint,field_tinyint,field_bigint,field_int_unsigned,field_smallint_unsigned,field_mediumint_unsigned,field_tinyint_unsigned,field_bigint_unsigned,field_year,field_decimal,field_decimal0,field_float,field_double,field_binary,field_varbinary,field_char,field_varchar,field_time,field_timestamp,field_date,field_datetime,field_enum,field_set,field_bit
 */
create procedure tst_test_insert_many01 ( )
  modifies sql data
begin
  drop temporary table if exists TST_TEMPO;

  create temporary table TST_TEMPO (
    tst_int        int(11),                           -- type: TST_FOO1.tst_c00
    tst_smallint   smallint(6),                       -- type: TST_FOO1.tst_c01
    tst_tinyint    tinyint(4),                        -- type: TST_FOO1.tst_c02
    tst_mediumint  mediumint(9),                      -- type: TST_FOO1.tst_c03
    tst_bigint     bigint(20),                        -- type: TST_FOO1.tst_c04
    tst_decimal    decimal(10, 2),                    -- type: TST_FOO1.tst_c05
    tst_float      float,                             -- type: TST_FOO1.tst_c06
    tst_double     double,                            -- type: TST_FOO1.tst_c07
    tst_bit        bit(8),                            -- type: TST_FOO1.tst_c08
    tst_date       date,                              -- type: TST_FOO1.tst_c09
    tst_datetime   datetime,                          -- type: TST_FOO1.tst_c10
    tst_timestamp  timestamp,                         -- type: TST_FOO1.tst_c11
    tst_time       time,                              -- type: TST_FOO1.tst_c12
    tst_year       year(4),                           -- type: TST_FOO1.tst_c13
    tst_char       char(10) character set utf8mb4,    -- type: TST_FOO1.tst_c14
    tst_varchar    varchar(10) character set utf8mb4, -- type: TST_FOO1.tst_c15
    tst_binary     binary(10),                        -- type: TST_FOO1.tst_c16
    tst_varbinary  varbinary(10),                     -- type: TST_FOO1.tst_c17
    tst_tinyblob   tinyblob,                          -- type: TST_FOO1.tst_c18
    tst_blob       blob,                              -- type: TST_FOO1.tst_c19
    tst_mediumblob mediumblob,                        -- type: TST_FOO1.tst_c20
    tst_longblob   longblob,                          -- type: TST_FOO1.tst_c21
    tst_tinytext   tinytext character set utf8mb4,    -- type: TST_FOO1.tst_c22
    tst_text       text character set utf8mb4,        -- type: TST_FOO1.tst_c23
    tst_mediumtext mediumtext character set utf8mb4,  -- type: TST_FOO1.tst_c24
    tst_longtext   longtext character set utf8mb4,    -- type: TST_FOO1.tst_c25
    primary key (tst_int)
  )
    engine = myisam;
end
