/**
 * Test for all possible types of parameters with maximum length.
 *
 * @param p_param14 Test parameter 14.
 * @param p_param15 Test parameter 15.
 * @param p_param16 Test parameter 16.
 * @param p_param17 Test parameter 17.
 */
create procedure tst_parameter_types03(p_param14 @tst_foo1.tst_c14%max-type@,
                                       p_param15 @tst_foo1.tst_c15%max-type@,
                                       p_param16 @tst_foo1.tst_c16%max-type@,
                                       p_param17 @tst_foo1.tst_c17%max-type@)
reads sql data
-- type: none
begin
  insert into TST_FOO1( tst_c14
  ,                     tst_c15
  ,                     tst_c16
  ,                     tst_c17 )
  values( p_param14
  ,       p_param15
   ,      p_param16
  ,       p_param17 )
  ;
end 
