/**
 * Test for all possible types of parameters excluding LOB's.
 *
 * @param p_param00 Test parameter 00.
 * @param p_param01 Test parameter 01.
 * @param p_param02 Test parameter 02.
 * @param p_param03 Test parameter 03.
 * @param p_param04 Test parameter 04.
 * @param p_param05 Test parameter 05.
 * @param p_param06 Test parameter 06.
 * @param p_param07 Test parameter 07.
 * @param p_param08 Test parameter 08.
 * @param p_param09 Test parameter 09.
 * @param p_param10 Test parameter 10.
 * @param p_param11 Test parameter 11.
 * @param p_param12 Test parameter 12.
 * @param p_param13 Test parameter 13.
 * @param p_param14 Test parameter 14.
 * @param p_param15 Test parameter 15.
 * @param p_param16 Test parameter 16.
 * @param p_param17 Test parameter 17.
 * @param p_param26 Test parameter 26.
 * @param p_param27 Test parameter 27.
 *
 * @type none
 */
create procedure tst_parameter_types01
(
  p_param00 int(11), --                              type: TST_FOO1.tst_c00
  p_param01 smallint(6), --                          type: TST_FOO1.tst_c01
  p_param02 tinyint(4), --                           type: TST_FOO1.tst_c02
  p_param03 mediumint(9), --                         type: TST_FOO1.tst_c03
  p_param04 bigint(20), --                           type: TST_FOO1.tst_c04
  p_param05 decimal(10, 2), --                       type: TST_FOO1.tst_c05
  p_param06 float, --                                type: TST_FOO1.tst_c06
  p_param07 double, --                               type: TST_FOO1.tst_c07
  p_param08 bit(8), --                               type: TST_FOO1.tst_c08
  p_param09 date, --                                 type: TST_FOO1.tst_c09
  p_param10 datetime, --                             type: TST_FOO1.tst_c10
  p_param11 timestamp, --                            type: TST_FOO1.tst_c11
  p_param12 time, --                                 type: TST_FOO1.tst_c12
  p_param13 year(4), --                              type: TST_FOO1.tst_c13
  p_param14 char(10) character set utf8mb4, --       type: TST_FOO1.tst_c14
  p_param15 varchar(10) character set utf8mb4, --    type: TST_FOO1.tst_c15
  p_param16 binary(10), --                           type: TST_FOO1.tst_c16
  p_param17 varbinary(10), --                        type: TST_FOO1.tst_c17
  p_param26 enum ('a','b') character set utf8mb4, -- type: TST_FOO1.tst_c26
  p_param27 set ('a','b') character set utf8mb4 --   type: TST_FOO1.tst_c27
)
  reads sql data
begin
  insert into TST_FOO1( tst_c00
                      , tst_c01
                      , tst_c02
                      , tst_c03
                      , tst_c04
                      , tst_c05
                      , tst_c06
                      , tst_c07
                      , tst_c08
                      , tst_c09
                      , tst_c10
                      , tst_c11
                      , tst_c12
                      , tst_c13
                      , tst_c14
                      , tst_c15
                      , tst_c16
                      , tst_c17
                      , tst_c26
                      , tst_c27)
  values ( p_param00
         , p_param01
         , p_param02
         , p_param03
         , p_param04
         , p_param05
         , p_param06
         , p_param07
         , p_param08
         , p_param09
         , p_param10
         , p_param11
         , p_param12
         , p_param13
         , p_param14
         , p_param15
         , p_param16
         , p_param17
         , p_param26
         , p_param27);
end 
